[[custom_groups]]
name = "ğŸ”° Proxy"
type = "select"
rule = [
    "[]ğŸ¯ DIRECT",
    ".*"
]

[[custom_groups]]
name = "ğŸ‡ºğŸ‡¸ us"
type = "select"
rule = [
    "(ç¾å›½|us)"
]

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° HK"
type = "select"
rule = [
    "(é¦™æ¸¯|hk)"
]

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ JP"
type = "select"
rule = [
    "(é¦™æ¸¯|hk)"
]

[[custom_groups]]
name = "ğŸ‡¨ğŸ‡³ TW"
type = "select"
rule = [
    "(é¦™æ¸¯|hk)"
]

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ SG"
type = "select"
rule = [
    "(é¦™æ¸¯|hk)"
]

 

[[custom_groups]]
name = "ğŸ“º NETFLIX"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ us",
    "[]ğŸ‡­ğŸ‡° hk",
    "[]ğŸ‡¨ğŸ‡³ tw",
    "[]ğŸ‡¸ğŸ‡¬ sg",
    "[]ğŸ¯ DefaultDirect",
]

[[custom_groups]]
name = "ğŸ“º DisneyPlus"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ us",
    "[]ğŸ‡­ğŸ‡° hk",
    "[]ğŸ‡¨ğŸ‡³ tw",
    "[]ğŸ‡¸ğŸ‡¬ sg",
    "[]ğŸ¯ DefaultDirect",
]

[[custom_groups]]
name = "ğŸ“º HboUsA"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ us",
    "[]ğŸ¯ DefaultDirect",
]

[[custom_groups]]
name = "ğŸ“º HboHK"
type = "select"
rule = [
    "[]ğŸ‡­ğŸ‡° hk",
    "[]ğŸ¯ DefaultDirect",
]

[[custom_groups]]
name = "ğŸŒ Global"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ us",
    "[]ğŸ‡­ğŸ‡° hk",
    "[]ğŸ‡¨ğŸ‡³ tw",
    "[]ğŸ‡¸ğŸ‡¬ sg",
    "[]ğŸ¯ DefaultDirect",
]

[[custom_groups]]
name = "ğŸŒ GlobalMedia"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ us",
    "[]ğŸ‡­ğŸ‡° hk",
    "[]ğŸ‡¨ğŸ‡³ tw",
    "[]ğŸ‡¸ğŸ‡¬ sg",
    "[]ğŸ¯ DefaultDirect",
]

[[custom_groups]]
name = "ğŸŒ Bilibili"
type = "select"
rule = [
    "[]ğŸ‡­ğŸ‡° hk",
    "[]ğŸ‡¨ğŸ‡³ tw",
    "[]ğŸ¯ DefaultDirect",
]

[[custom_groups]]
name = "â“‚ï¸ Microsoft"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ us",
    "[]ğŸ‡­ğŸ‡° hk",
    "[]ğŸ‡¨ğŸ‡³ tw",
    "[]ğŸ‡¸ğŸ‡¬ sg",
    "[]ğŸ¯ DIRECT",
]

[[custom_groups]]
name = "ğŸ Apple"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ us",
    "[]ğŸ‡­ğŸ‡° hk",
    "[]ğŸ‡¨ğŸ‡³ tw",
    "[]ğŸ‡¸ğŸ‡¬ sg",
    "[]ğŸ¯ DefaultDirect",
]

[[custom_groups]]
name = "ğŸ® Steam"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ us",
    "[]ğŸ‡­ğŸ‡° hk",
    "[]ğŸ‡¨ğŸ‡³ tw",
    "[]ğŸ‡¸ğŸ‡¬ sg",
]


[[custom_groups]]
name = "ğŸ“º YouTub"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ us",
    "[]ğŸ‡­ğŸ‡° hk",
    "[]ğŸ‡¨ğŸ‡³ tw",
    "[]ğŸ‡¸ğŸ‡¬ sg",
]

[[custom_groups]]
name = "ğŸŒ Google"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ us",
    "[]ğŸ‡­ğŸ‡° hk",
    "[]ğŸ‡¨ğŸ‡³ tw",
    "[]ğŸ‡¸ğŸ‡¬ sg",
]

[[custom_groups]]
name = "ğŸ¶ TikTok"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ us",
    "[]ğŸ‡­ğŸ‡° hk",
    "[]ğŸ‡¨ğŸ‡³ tw",
    "[]ğŸ‡¸ğŸ‡¬ sg",
]

[[custom_groups]]
name = "ğŸ“² Telegram"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ us",
    "[]ğŸ‡­ğŸ‡° hk",
    "[]ğŸ‡¨ğŸ‡³ tw",
    "[]ğŸ‡¸ğŸ‡¬ sg",
]

[[custom_groups]]
name = "ğŸ¯ DefaultDirect"
type = "select"
rule = [
    "[]ğŸ¯ DIRECT",
]

[[custom_groups]]
name = "ğŸš« AdBlock"
type = "select"
rule = [
    "[]REJECT", 
    "[]ğŸ¯ DefaultDirect",
]

[[custom_groups]]
name = "ğŸŸ Other"
type = "select"
rule = [
    "[]ğŸ”° Proxy",
    "[]ğŸ¯ DefaultDirect"
]
