[[custom_groups]]
name = "ğŸ”° Proxy"
type = "select"
rule = [
    "[]ğŸ¯ Mainland",
    ".*"
]

[[custom_groups]]
name = "ğŸ‡ºğŸ‡¸ us"
type = "select"
rule = [
    "(ç¾å›½|us)"
]

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° hk"
type = "select"
rule = [
    "(é¦™æ¸¯|hk)"
]

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ jp"
type = "select"
rule = [
    "(æ—¥æœ¬|jp)"
]

[[custom_groups]]
name = "ğŸ‡¨ğŸ‡³ tw"
type = "select"
rule = [
    "(å°æ¹¾|TW|tw)"
]

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ sg"
type = "select"
rule = [
    "(æ–°åŠ å¡|sg|SG)"
]

 

[[custom_groups]]
name = "ğŸ“º NETFLIX"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ us",
    "[]ğŸ‡­ğŸ‡° hk",
    "[]ğŸ‡¨ğŸ‡³ tw",
    "[]ğŸ‡¸ğŸ‡¬ sg",
    "[]ğŸ¯ Mainland",
]

[[custom_groups]]
name = "ğŸ“º DisneyPlus"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ us",
    "[]ğŸ‡­ğŸ‡° hk",
    "[]ğŸ‡¨ğŸ‡³ tw",
    "[]ğŸ‡¸ğŸ‡¬ sg",
    "[]ğŸ¯ Mainland",
]

[[custom_groups]]
name = "ğŸ“º HboUsA"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ us",
    "[]ğŸ¯ Mainland",
]

[[custom_groups]]
name = "ğŸ“º HboHK"
type = "select"
rule = [
    "[]ğŸ‡­ğŸ‡° hk",
    "[]ğŸ¯ Mainland",
]

[[custom_groups]]
name = "ğŸŒ Global"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ us",
    "[]ğŸ‡­ğŸ‡° hk",
    "[]ğŸ‡¨ğŸ‡³ tw",
    "[]ğŸ‡¸ğŸ‡¬ sg",
    "[]ğŸ¯ Mainland",
]

[[custom_groups]]
name = "ğŸŒ GlobalMedia"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ us",
    "[]ğŸ‡­ğŸ‡° hk",
    "[]ğŸ‡¨ğŸ‡³ tw",
    "[]ğŸ‡¸ğŸ‡¬ sg",
    "[]ğŸ¯ Mainland",
]

[[custom_groups]]
name = "ğŸŒ Bilibili"
type = "select"
rule = [
    "[]ğŸ‡­ğŸ‡° hk",
    "[]ğŸ‡¨ğŸ‡³ tw",
    "[]ğŸ¯ Mainland",
]

[[custom_groups]]
name = "â“‚ï¸ Microsoft"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ us",
    "[]ğŸ‡­ğŸ‡° hk",
    "[]ğŸ‡¨ğŸ‡³ tw",
    "[]ğŸ‡¸ğŸ‡¬ sg",
    "[]ğŸ¯ Mainland",
]

[[custom_groups]]
name = "ğŸ Apple"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ us",
    "[]ğŸ‡­ğŸ‡° hk",
    "[]ğŸ‡¨ğŸ‡³ tw",
    "[]ğŸ‡¸ğŸ‡¬ sg",
    "[]ğŸ¯ Mainland",
]

[[custom_groups]]
name = "ğŸ® Steam"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ us",
    "[]ğŸ‡­ğŸ‡° hk",
    "[]ğŸ‡¨ğŸ‡³ tw",
    "[]ğŸ‡¸ğŸ‡¬ sg",
]


[[custom_groups]]
name = "ğŸ“º YouTub"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ us",
    "[]ğŸ‡­ğŸ‡° hk",
    "[]ğŸ‡¨ğŸ‡³ tw",
    "[]ğŸ‡¸ğŸ‡¬ sg",
]

[[custom_groups]]
name = "ğŸŒ Google"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ us",
    "[]ğŸ‡­ğŸ‡° hk",
    "[]ğŸ‡¨ğŸ‡³ tw",
    "[]ğŸ‡¸ğŸ‡¬ sg",
]

[[custom_groups]]
name = "ğŸ¶ TikTok"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ us",
    "[]ğŸ‡­ğŸ‡° hk",
    "[]ğŸ‡¨ğŸ‡³ tw",
    "[]ğŸ‡¸ğŸ‡¬ sg",
]

[[custom_groups]]
name = "ğŸ“² Telegram"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ us",
    "[]ğŸ‡­ğŸ‡° hk",
    "[]ğŸ‡¨ğŸ‡³ tw",
    "[]ğŸ‡¸ğŸ‡¬ sg",
]

[[custom_groups]]
name = "ğŸ¯ Mainland"
type = "select"
rule = [
    "[]DIRECT",
]

[[custom_groups]]
name = "ğŸš« AdBlock"
type = "select"
rule = [
    "[]REJECT", 
    "[]ğŸ¯ Mainland",
]

[[custom_groups]]
name = "ğŸŸ Other"
type = "select"
rule = [
    "[]ğŸ”° Proxy",
    "[]ğŸ¯ Mainland"
]
