[[rulesets]]
group = "ğŸ“º NETFLIX"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Netflix/Netflix.list"

[[rulesets]]
group = "ğŸ“º DisneyPlus"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Disney/Disney.list"

[[rulesets]]
group = "ğŸ“º HboUsA"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/HBOUSA/HBOUSA.list"

[[rulesets]]
group = "ğŸ“º HboHK"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/HBOHK/HBOHK.list"

[[rulesets]]
group = "ğŸŒ Bilibili"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/BiliBili/BiliBili.list"

[[rulesets]]
group = "â“‚ï¸ Microsoft"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Microsoft/Microsoft.list"

[[rulesets]]
group = "ğŸ Apple"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Apple/Apple.list"

[[rulesets]]
group = "ğŸ® Steam"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Steam/Steam.list"

[[rulesets]]
group = "ğŸ“º YouTub"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/YouTube/YouTube.list"

[[rulesets]]
group = "ğŸŒ Google"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Google/Google.list"

[[rulesets]]
group = "ğŸ¶ TikTok"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/TikTok/TikTok.list"

[[rulesets]]
group = "ğŸ“² Telegram"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Telegram/Telegram.list"


[[rulesets]]
group = "ğŸš« AdBlock"
ruleset = "https://raw.githubusercontent.com/NobyDa/Script/master/Surge/AdRule.list"

[[rulesets]]
group = "ğŸš« AdBlock"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Hijacking/Hijacking.list"

[[rulesets]]
group = "ğŸ¯ Mainland"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Lan/Lan.list"

[[rulesets]]
group = "ğŸ¯ Mainland"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/China/China.list"

[[rulesets]]
group = "ğŸ¯ Mainland"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/ChinaIPs/ChinaIPs.list"

[[rulesets]]
group = "ğŸ¯ Mainland"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/PrivateTracker/PrivateTracker.list"

[[rulesets]]
group = "ğŸŒ Global"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Global/Global.list"

[[rulesets]]
group = "ğŸŒ GlobalMedia"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/GlobalMedia/GlobalMedia.list"

[[rulesets]]
group = "ğŸ¯ Mainland"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸŸ Other"
ruleset = "[]FINAL"